### PR TITLE
fix: build-json moving subsection

### LINKED ISSUE #1786: build-json moving subsection key in JSON
**Describe the bug**
The `build-json` command is moving the subsection key in the json files, which modifies all of the json files.

**To Reproduce**
Run `build-sqlite` and then `build-json`

**Expected behavior**
```
    "id": "CSQ",
    "sttm_id": null,
    "writer": "SGPC",
    "section": "Ardaas",
    "subsection": "Ardaas",
```

**Screenshots**
```
    "id": "CSQ",
    "sttm_id": null,
    "subsection": null,
    "writer": "SGPC",
    "section": "Ardaas",
```

### PR DESCRIPTION
**Pull request by saihaj**
### Summary of PR
Explicitly set the keys instead of spreading. This helps fix the moving around of subsection key issue.

### Tests for unexpected behavior
- Subsection key doesn't move

### Time spent on PR
3.5 hours

### Linked issues
Fix #1786 

### Reviewers
@Harjot1Singh @Sarabveer

### CODE REVIEW

File: lib/build-json.js [hunk 1]
```diff
@@ -124,17 +124,13 @@ const processLines = async () => {
...
       [ nameEnglish ]: await Promise.all( shabads.map( async shabad => ( { //! Do not destructure
       // Generate JSON with desired keys for Shabad
-        ...snakeCaseKeys( {
-          ...shabad,
-          writerId: undefined,
-          compositionId: undefined,
-          sectionId: undefined,
-          orderId: undefined,
-          subsectionId: undefined,
+        ...{
```
Comment (Harjot1Singh) [inline lib/build-json.js:127]: You don't need to spread an object inside an object.

Also, was `snakeCaseKeys` changing the order? What was the culprit?

Would you be able to keep `snakeCaseKeys` and just not spread `...shabad`?

Comment (saihaj) [reply lib/build-json.js:127]: `snakeCaseKeys` was working fine.... I don't know what was messing things. We can keep `snakeCaseKeys` but don't think we need it since we are hardcoding the keys

File: data/Sri Guru Granth Sahib Ji/0136.json [hunk 2]
```diff
@@ -1,4 +1,886 @@
...
+  {
+    "id": "D1Z",
+    "sttm_id": 358,
+    "writer": "Guru Arjan Dev Ji",
+    "section": "Raag Maajh",
+    "subsection": null,
+    "lines": [
+      {
+        "id": "6QBR",
+        "source_page": 136,
```
Comment (saihaj) [inline data/Sri Guru Granth Sahib Ji/0136.json:11]: source page matches the file page

File: data/Sri Guru Granth Sahib Ji/0368.json [hunk 3]
```diff
@@ -1657,590 +1657,5 @@
...
-  {
-    "id": "P5L",
-    "sttm_id": 1433,
-    "writer": "Guru Ramdas Ji",
-    "section": "Raag Aasaa",
-    "subsection": null,
-    "lines": [
-      {
-        "id": "7PKC",
-        "source_page": 369,
```
Comment (saihaj) [inline data/Sri Guru Granth Sahib Ji/0368.json:1670]: removed the page number that wasn't suppose to be here. @Sarabveer is this expected?

File: data/Sri Guru Granth Sahib Ji/0369.json [hunk 4]
```diff
@@ -1,4 +1,589 @@
...
+  {
+    "id": "P5L",
+    "sttm_id": 1433,
+    "writer": "Guru Ramdas Ji",
+    "section": "Raag Aasaa",
+    "subsection": null,
+    "lines": [
+      {
+        "id": "7PKC",
+        "source_page": 369,
```
Comment (saihaj) [inline data/Sri Guru Granth Sahib Ji/0369.json:11]: Got added from 0368.json

File: data/Sri Guru Granth Sahib Ji/0133.json [hunk 5]
```diff
@@ -1465,4856 +1465,5 @@
...
-  {
-    "id": "HSB",
-    "sttm_id": 358,
-    "writer": "Guru Arjan Dev Ji",
-    "section": "Raag Maajh",
-    "subsection": null,
-    "lines": [
-      {
-        "id": "F858",
-        "source_page": 134,
```
Comment (saihaj) [inline data/Sri Guru Granth Sahib Ji/0133.json:1478]: Page number doesn't match so this is moved to other file

**Comment by Sarabveer** [comment]
Some are due to https://github.com/ShabadOS/database/pull/1486

`build-sqlite` and then `build-json` wasn't run

**Comment by saihaj** [comment]
Do we want to then make changes here? Or reopen that pr, rebase it with this and then run `build-json` ?

**Comment by Sarabveer** [comment]
LGTM on the Data side of things

File: lib/build-json.js (hunk 1 above)
Comment (Harjot1Singh) [reply lib/build-json.js:127]: Keep snakeCaseKeys, rebase it back on so that there are the same two commit you have right now, since snake_case is flagged up by ESLint so we tend to avoid it, and in the future, we are going to move to it fully.

**Comment by Harjot1Singh** [comment]
`fix(build)` is not a scope btw, `build:` is probably the right scope for this
